// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/RabotaemActivno/pulse/internal/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPostgres creates a new instance of MockPostgres. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPostgres(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPostgres {
	mock := &MockPostgres{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPostgres is an autogenerated mock type for the Postgres type
type MockPostgres struct {
	mock.Mock
}

type MockPostgres_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPostgres) EXPECT() *MockPostgres_Expecter {
	return &MockPostgres_Expecter{mock: &_m.Mock}
}

// FindToken provides a mock function for the type MockPostgres
func (_mock *MockPostgres) FindToken(ctx context.Context, tokenHash string) (domain.Token, error) {
	ret := _mock.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for FindToken")
	}

	var r0 domain.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.Token, error)); ok {
		return returnFunc(ctx, tokenHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.Token); ok {
		r0 = returnFunc(ctx, tokenHash)
	} else {
		r0 = ret.Get(0).(domain.Token)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPostgres_FindToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindToken'
type MockPostgres_FindToken_Call struct {
	*mock.Call
}

// FindToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockPostgres_Expecter) FindToken(ctx interface{}, tokenHash interface{}) *MockPostgres_FindToken_Call {
	return &MockPostgres_FindToken_Call{Call: _e.mock.On("FindToken", ctx, tokenHash)}
}

func (_c *MockPostgres_FindToken_Call) Run(run func(ctx context.Context, tokenHash string)) *MockPostgres_FindToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostgres_FindToken_Call) Return(token domain.Token, err error) *MockPostgres_FindToken_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockPostgres_FindToken_Call) RunAndReturn(run func(ctx context.Context, tokenHash string) (domain.Token, error)) *MockPostgres_FindToken_Call {
	_c.Call.Return(run)
	return _c
}

// LoginUser provides a mock function for the type MockPostgres
func (_mock *MockPostgres) LoginUser(ctx context.Context, email string, password string) (uuid.UUID, error) {
	ret := _mock.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for LoginUser")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (uuid.UUID, error)); ok {
		return returnFunc(ctx, email, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) uuid.UUID); ok {
		r0 = returnFunc(ctx, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPostgres_LoginUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoginUser'
type MockPostgres_LoginUser_Call struct {
	*mock.Call
}

// LoginUser is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *MockPostgres_Expecter) LoginUser(ctx interface{}, email interface{}, password interface{}) *MockPostgres_LoginUser_Call {
	return &MockPostgres_LoginUser_Call{Call: _e.mock.On("LoginUser", ctx, email, password)}
}

func (_c *MockPostgres_LoginUser_Call) Run(run func(ctx context.Context, email string, password string)) *MockPostgres_LoginUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPostgres_LoginUser_Call) Return(uUID uuid.UUID, err error) *MockPostgres_LoginUser_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockPostgres_LoginUser_Call) RunAndReturn(run func(ctx context.Context, email string, password string) (uuid.UUID, error)) *MockPostgres_LoginUser_Call {
	_c.Call.Return(run)
	return _c
}

// LogoutUser provides a mock function for the type MockPostgres
func (_mock *MockPostgres) LogoutUser(ctx context.Context, tokenHash string) error {
	ret := _mock.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for LogoutUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, tokenHash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPostgres_LogoutUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogoutUser'
type MockPostgres_LogoutUser_Call struct {
	*mock.Call
}

// LogoutUser is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockPostgres_Expecter) LogoutUser(ctx interface{}, tokenHash interface{}) *MockPostgres_LogoutUser_Call {
	return &MockPostgres_LogoutUser_Call{Call: _e.mock.On("LogoutUser", ctx, tokenHash)}
}

func (_c *MockPostgres_LogoutUser_Call) Run(run func(ctx context.Context, tokenHash string)) *MockPostgres_LogoutUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostgres_LogoutUser_Call) Return(err error) *MockPostgres_LogoutUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPostgres_LogoutUser_Call) RunAndReturn(run func(ctx context.Context, tokenHash string) error) *MockPostgres_LogoutUser_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterUser provides a mock function for the type MockPostgres
func (_mock *MockPostgres) RegisterUser(ctx context.Context, user domain.User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPostgres_RegisterUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterUser'
type MockPostgres_RegisterUser_Call struct {
	*mock.Call
}

// RegisterUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user domain.User
func (_e *MockPostgres_Expecter) RegisterUser(ctx interface{}, user interface{}) *MockPostgres_RegisterUser_Call {
	return &MockPostgres_RegisterUser_Call{Call: _e.mock.On("RegisterUser", ctx, user)}
}

func (_c *MockPostgres_RegisterUser_Call) Run(run func(ctx context.Context, user domain.User)) *MockPostgres_RegisterUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.User
		if args[1] != nil {
			arg1 = args[1].(domain.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostgres_RegisterUser_Call) Return(err error) *MockPostgres_RegisterUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPostgres_RegisterUser_Call) RunAndReturn(run func(ctx context.Context, user domain.User) error) *MockPostgres_RegisterUser_Call {
	_c.Call.Return(run)
	return _c
}

// SaveRefreshToken provides a mock function for the type MockPostgres
func (_mock *MockPostgres) SaveRefreshToken(ctx context.Context, id uuid.UUID, userID uuid.UUID, tokenHash string, expiresAt time.Time) error {
	ret := _mock.Called(ctx, id, userID, tokenHash, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for SaveRefreshToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, time.Time) error); ok {
		r0 = returnFunc(ctx, id, userID, tokenHash, expiresAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPostgres_SaveRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveRefreshToken'
type MockPostgres_SaveRefreshToken_Call struct {
	*mock.Call
}

// SaveRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
//   - tokenHash string
//   - expiresAt time.Time
func (_e *MockPostgres_Expecter) SaveRefreshToken(ctx interface{}, id interface{}, userID interface{}, tokenHash interface{}, expiresAt interface{}) *MockPostgres_SaveRefreshToken_Call {
	return &MockPostgres_SaveRefreshToken_Call{Call: _e.mock.On("SaveRefreshToken", ctx, id, userID, tokenHash, expiresAt)}
}

func (_c *MockPostgres_SaveRefreshToken_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID, tokenHash string, expiresAt time.Time)) *MockPostgres_SaveRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockPostgres_SaveRefreshToken_Call) Return(err error) *MockPostgres_SaveRefreshToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPostgres_SaveRefreshToken_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID, tokenHash string, expiresAt time.Time) error) *MockPostgres_SaveRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}
